### ISSUE TITLE
composer.json does not allow PHP 7.4

### ISSUE THREAD

**Issue by DBMdebussac** [owebia/magento2-module-shared-php-config#2]
Hello, when we try to require owebia/magento2-module-advanced-shipping ^2.8 with PHP7.4, there is a compatibility issue with  owebia/magento2-module-shared-php-config.

Could you please allow PHP7.4 ? #1 

Thanks in advance and for your modules

**Comment by owebia** [comment]
Fixed by commit https://github.com/owebia/magento2-module-shared-php-config/commit/3107c348218b0d3ae0204f7a9db209d280364989, thanks.
Available in version 3.0.1

**Comment by MridulKumar1424** [comment]
![image](https://user-images.githubusercontent.com/53964209/203500606-d89a9646-715f-493c-9914-8c7281b7046f.png)
I am facing this issue on di compile

**Comment by owebia** [comment]
Hi, how did you install the module?

Did you follow the instructions given in the README file?

**Comment by MridulKumar1424** [comment]
Yes, i read it and installed it successfully by installing another module
which was required.
Thanks.
