### ISSUE TITLE
Magento 2.4.4 Support

### ISSUE THREAD

**Issue by mtytula** [owebia/magento2-module-shared-php-config#5]
There is an execption thrown at the start of execution bin/magento setup:di:compile 

`PHP Fatal error:  Declaration of Owebia\SharedPhpConfig\Logger\Handler::write(array $record) must be compatible with Magento\Framework\Logger\Handler\Base::write(array $record): void in /var/www/vendor/owebia/magento2-module-shared-php-config/Logger/Handler.php on line 27`

`Fatal error: Declaration of Owebia\SharedPhpConfig\Logger\Handler::write(array $record) must be compatible with Magento\Framework\Logger\Handler\Base::write(array $record): void in /var/www/vendor/owebia/magento2-module-shared-php-config/Logger/Handler.php on line 27
`

**Comment by owebia** [comment]
This has been fixed in the latest version released today.

Could you confirm that you don't have the exception anymore after updating the module?

Best Regards,
A.L.

**Comment by owebia** [comment]
(PS: related to PHP 8.1 support)
