### ISSUE TITLE
not working on magento 2.4.6

### ISSUE THREAD

**Issue by harishkhant** [owebia/magento2-module-shared-php-config#9]
https://dev.comartex.com/checkout/cart/#:~:text=Error%3A%20Cannot%20instantiate%20interface%20Owebia%5CSharedPhpConfig%5CApi%5CParserInterface%20in%20/home/dev_comartex/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php%3A121%0AStack%20trace%3A

![image](https://github.com/owebia/magento2-module-shared-php-config/assets/64633051/04fcd0f2-20ed-404a-a608-55751ee3191a)

owebia/magento2-module-shared-php-config after installing this module we faced an error on the checkout page.

**Comment by owebia** [comment]
Closing duplicate of https://github.com/owebia/magento2-module-advanced-shipping/issues/115
